# Generated by Django 3.0.7 on 2020-10-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20201025_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Status',
            field=models.CharField(choices=[('pending', 'pending'), ('cancelled', 'cancelled'), ('confirmed', 'confirmed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Day_Range',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=9, verbose_name='Day'),
        ),
    ]
