# Generated by Django 3.0.7 on 2020-10-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20201026_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Day_Range',
            field=models.DateTimeField(verbose_name='Date and Time'),
        ),
    ]
