# Generated by Django 3.0.7 on 2020-10-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_auto_20201027_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Day_Range',
            field=models.DateField(verbose_name='Date and Time'),
        ),
    ]
