# Generated by Django 3.0.7 on 2020-10-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_auto_20201027_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Hour',
            field=models.CharField(choices=[('0', '09:00'), ('0', '10:00'), ('0', '11:00'), ('0', '12:00'), ('0', '13:00'), ('0', '14:00'), ('0', '15:00'), ('0', '16:00'), ('0', '17:00')], default='00:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Day_Range',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=9, verbose_name='Date and Time'),
        ),
    ]
