# Generated by Django 3.0.7 on 2020-10-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_auto_20201027_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Hour',
            field=models.CharField(choices=[('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00')], default='09:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Service',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Healthy Life Plan', 'Healthy Life Plan'), ('Diet and Workout', 'Diet and Workout'), ('Kinetotherapy', 'Kinetotherapy')], default='Service1', max_length=17),
        ),
    ]
