# Generated by Django 3.0.7 on 2020-10-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_auto_20201027_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Day_Range',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=9, verbose_name='Day'),
        ),
    ]
