# Generated by Django 3.0.7 on 2020-10-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='consultation.jpg', upload_to='service_pics'),
        ),
    ]
